name: Node CI

on: 
  push:
    branches:
      - next

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g lerna
        npm install -g yarn
        yarn
        yarn init-vendor
        yarn build-vendor
        lerna run build --scope @matechs/*
        lerna run test --scope @matechs/*
      env:
        CI: true
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}