name: Node CI

on:
  push:
    branches:
      - master
      - preview/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install -g yarn
          yarn
          yarn ultra -r build
          yarn ultra -r tc
          yarn ultra -r lint
          yarn jest --detectOpenHandles
          cp .ci.npmrc .npmrc
          yarn lerna publish from-package --yes
        env:
          CI: "true"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
