name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install -g yarn
          yarn
          yarn lerna run build --scope @matechs/core
          yarn jest shaking/core --detectOpenHandles
          cd shaking/core
          yarn tsc bench/*.ts
          node bench/index.js
          node bench/nestedChain.js
          node bench/nestedMap.js
        env:
          CI: "true"

      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
